[tool.poetry]
name = "PySpek"
version = "0.1.0"
description = ""
authors = ["Federico García <garciafedericoagustin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
miniaudio = "^1.44"
svgwrite = "^1.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
