name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    
    - name: Install Poetry (latest version)
      uses: Gr1N/setup-poetry@v4
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Test
      run: |
        poetry run python -m pytest -v tests/
